# Generated by Django 3.0.3 on 2020-02-14 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.TextField()),
                ('student_last_name', models.TextField()),
                ('student_email', models.EmailField(max_length=254)),
                ('student_cellphone', models.TextField()),
                ('counselor_name', models.CharField(choices=[('MARINO', 'Ms. Marino'), ('ROBINSON', 'Mr. Robinson')], max_length=50)),
                ('college_deadline', models.CharField(max_length=50)),
                ('college_name', models.CharField(max_length=100)),
                ('delivery_option', models.CharField(choices=[('GEORGIA_UNIVERSITY', 'Georgia College/ University'), ('COMMONAPP', 'Common App'), ('ONLINE_PORTAL', 'Online Portal'), ('PAPER', 'Paper/ Hard Copy')], max_length=50)),
                ('date_request', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
