# Generated by Django 3.0.3 on 2020-02-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecommendation',
            name='delivery_option',
            field=models.CharField(choices=[('GEORGIAUNIVERSITY', 'Georgia College/ University'), ('COMMONAPP', 'Common App'), ('ONLINEPORTAL', 'Online Portal'), ('PAPER', 'Paper/ Hard Copy')], max_length=50),
        ),
    ]
