# Generated by Django 3.0.3 on 2020-02-15 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_auto_20200215_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecommendation',
            name='counselor_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='delivery_option',
            field=models.CharField(max_length=50),
        ),
    ]
