# Generated by Django 3.0.3 on 2020-02-15 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0004_auto_20200215_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecommendation',
            name='college_deadline',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='college_name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='counselor_name',
            field=models.TextField(choices=[('1', 'Ms. Marino'), ('2', 'Mr. Robinson')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='delivery_option',
            field=models.TextField(choices=[('GEORGIAUNIVERSITY', 'Georgia College/ University'), ('COMMONAPP', 'Common App'), ('ONLINEPORTAL', 'Online Portal'), ('PAPER', 'Paper/ Hard Copy')], max_length=50),
        ),
    ]
