# Generated by Django 3.0.3 on 2020-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_auto_20200215_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecommendation',
            name='college_deadline',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='counselor_name',
            field=models.CharField(choices=[('1', 'Ms. Marino'), ('2', 'Mr. Robinson')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='delivery_option',
            field=models.CharField(choices=[('GEORGIAUNIVERSITY', 'Georgia College/ University'), ('COMMONAPP', 'Common App'), ('ONLINEPORTAL', 'Online Portal'), ('PAPER', 'Paper/ Hard Copy')], max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='student_cellphone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='student_first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecommendation',
            name='student_last_name',
            field=models.CharField(max_length=50),
        ),
    ]
