# Generated by Django 3.0.3 on 2020-02-15 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Updates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_to_display', models.CharField(choices=[('1', 'Graduation Coach & Credit Recovery'), ('2', 'Scholarships and Financial Aid'), ('3', 'Summer School & Virtual School'), ('4', 'Seniors'), ('5', 'SAT/ACT & Test Prep Opportunities'), ('6', 'New Enrollment'), ('7', 'Dual Enrollment'), ('8', 'Raising 9th Graders')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=5000)),
                ('image', models.ImageField(upload_to='')),
                ('external_url', models.CharField(max_length=100)),
                ('counselor_name', models.CharField(max_length=50)),
                ('data_of_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
