# Generated by Django 3.0.3 on 2020-02-15 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='updates',
            old_name='data_of_published',
            new_name='data_published',
        ),
    ]
