# Generated by Django 3.0.3 on 2020-02-16 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200215_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='external_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
