# Generated by Django 3.0.3 on 2020-02-16 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200216_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='updates',
            name='content',
            field=models.TextField(max_length=5000),
        ),
    ]
